routes/web.php
<?php
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
// Start File Upload
Route::get('/file', 'FileController@index')->name('viewfile');
Route::get('/file/upload', 'FileController@create')->name('formfile');
Route::post('/file/upload', 'FileController@store')->name('uploadfile');
Route::delete('/file/{id}', 'FileController@destroy')->name('deletefile');
Route::get('/file/download/{id}', 'FileController@show')->name('downloadfile');
Route::get('/file/email/{id}', 'FileController@edit')->name('emailfile');
Route::post('/file/dropzone', 'FileController@dropzone')->name('dropzone');
// End File Upload
//Clear route cache:
Route::get('/route-cache', function () {
    $exitCode = Artisan::call('route:cache');
    return 'Routes cache cleared';
});

//Clear config cache:
Route::get('/config-cache', function () {
    $exitCode = Artisan::call('config:cache');
    return 'Config cache cleared';
});

// Clear application cache:
Route::get('/clear-cache', function () {
    $exitCode = Artisan::call('cache:clear');
    return 'Application cache cleared';
});

// Clear view cache:
Route::get('/view-clear', function () {
    $exitCode = Artisan::call('view:clear');
    return 'View cache cleared';
});

Route::get('/logout', function () {
    Session::flush();
    return redirect('/');
});

// Route::post('/send_session_data', function () {
//     return ['status'=>'success'];
//     // dd("session data routs worked.");
// });

Auth::routes();

Route::get('/', 'HomeController@index')->name('/');
Route::post('registration', 'RegisterController@store')->name('registration');
// Route::get('/roles', 'PermissionController@Permission');

Route::group(['middleware' => ['role:admin']], function () {
    Route::get('dashboard', 'Admin\DashboardController@index')->name('dashboard');
    Route::resource('users', 'UserController');
    Route::resource('appointments', 'AppointmentController');
    Route::get('set_appointment/{id}', 'AppointmentController@set_appointment')->name('set_appointment');
    Route::get('prescription_edit/{id}', 'AppointmentController@prescription_edit')->name('prescription_edit');
    Route::post('prescription_update/{id}', 'AppointmentController@prescription_update')->name('prescription_update');
    Route::post('approve_user/{id}', 'UserController@approve_user')->name('approve_user');
    Route::post('pending_user/{id}', 'UserController@pending_user')->name('pending_user');

    Route::get('settings', 'SettingsController@index')->name('settings');
    Route::put('profile-update', 'SettingsController@updateProfile')->name('profile-update');
    Route::put('password-update', 'SettingsController@updatePassword')->name('password-update');
    Route::get('message', 'MessageController@index')->name('message');
    Route::post('send_message', 'MessageController@message')->name('send_message');
    Route::get('chat/{id}/{room}/{name}', 'LiveChatController@chat')->name('chat');
    Route::post('send_session_data', 'LiveChatController@send_session_data')->name('send_session_data');
    // Route::post('send_session_data', function (Request $request) {
    //     return response()->json(['status' => $request->all()]);
    //     // dd("session data routs worked.");
    // });

    // hasibul

    Route::resource('clinic', 'ClinicController');
    Route::resource('slot', 'SlotController');
    Route::resource('day', 'DayController');
    Route::get('followup_patient', 'Admin\DashboardController@followup_patient_list')->name('followup_patient');
    Route::get('new_patient', 'Admin\DashboardController@new_patient_list')->name('new_patient');
    Route::get('all_patient', 'Admin\DashboardController@all_patient_list')->name('all_patient');
    Route::get('emergency', 'Admin\DashboardController@emergency')->name('emergency');

    Route::get('set_appointment/{id}/doctor_slot/{doc_id}/{visit_date}', 'AppointmentController@doctorAvailbleSlot')->name('doctor_slot');

    Route::get('prescription_download/{id}', 'AppointmentController@prescriptionDownload')->name('prescription_download');
});

resources/views/layouts/backend/partial/sidebar.blade.php
<aside id="leftsidebar" class="sidebar">
            <!-- User Info -->
            <div class="user-info">
                <div class="image" >
                    <img src=" @if( is_null(Auth::user()->image)) {{ url('storage/app/public/profile/no_profile.png') }} @else {{ url('storage/app/public/profile/'.Auth::user()->image) }} @endif " width="48" height="48" alt="User" />
                </div>
                <div class="info-container">
                    <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ Auth::user()->name }} </div>
                    <div class="email">{{ Auth::user()->email }} </div>
                    <div class="btn-group user-helper-dropdown">
                        <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                        <ul class="dropdown-menu pull-right">
                            <li>
                                <a href="">
                                <i class="material-icons">settings</i>Settings</a>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                            	<a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        <i class="material-icons">input</i>Sign Out
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                </form>

                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- #User Info -->
            <!-- Menu -->
            <div class="menu">
                <ul class="list">
                    <li class="header">MAIN NAVIGATION</li>

                    @role('user')
                    <li class="{{Request::is('dashboard') ? 'active' : ''}}">
                        <a href="{{route('dashboard')}}">
                            <i class="material-icons">home</i>
                            <span>Home</span>
                        </a>
                    </li>


                   
                    @if(auth()->check() && auth()->user()->hasRole('super-admin'))
                    <li class="{{Request::is('users') ? 'active' : ''}}">
                        <a href="{{route('users.index')}}">
                            <i class="material-icons">person_add</i>
                            <span>New User</span>
                        </a>
                    </li>
                    @endif
                  
                    @role('user')


                    @if(auth()->check() && auth()->user()->hasRole('admin') || auth()->user()->hasRole('power-user') || auth()->user()->hasRole('super-admin'))
                    {{--
                    <li class="header">INFORMATION</li>
                    <li class="{{Request::is('all_patient') ? 'active' : ''}}">
                        <a href="{{route('all_patient')}}">
                            <i class="material-icons">supervised_user_circle</i>
                            <span>Total Patients</span>
                        </a>
                    </li>

                    <li class="{{Request::is('followup_patient') ? 'active' : ''}}">
                        <a href="{{route('followup_patient')}}">
                            <i class="material-icons">person_search</i>
                            <span>Followup Patient</span>
                        </a>
                    </li>

                    <li class="{{Request::is('new_patient') ? 'active' : ''}}">
                        <a href="{{route('new_patient')}}">
                            <i class="material-icons">person_add</i>
                            <span>New Appointment</span>
                        </a>
                    </li>

                    <li class="{{Request::is('emergency') ? 'active' : ''}}">
                        <a href="{{route('emergency')}}">
                            <i class="material-icons">airline_seat_individual_suite</i>
                            <span>Emergency</span>
                        </a>
                    </li>
                    --}}
                    @endif
                   

                    <li class="header">System</li>
                    <li class="{{Request::is('settings') ? 'active' : ''}}">
                        <a href="{{route('settings')}}">
                            <i class="material-icons">settings</i>
                            <span>Settings</span>
                        </a>
                    </li>
                    @if(auth()->check() && auth()->user()->hasRole('admin'))
                    <li class="{{Request::is('slot') ? 'active' : ''}}">
                        <a href="{{route('slot.index')}}">
                            <i class="material-icons">date_range</i>
                            <span>Create Time Schedule</span>
                        </a>
                    </li>
                    @endif
                    @if(auth()->check() && auth()->user()->hasRole('super-admin'))
                    <li class="{{Request::is('slot') ? 'active' : ''}}">
                        <a href="{{route('slot.index')}}">
                            <i class="material-icons">date_range</i>
                            <span>Create Time Schedule</span>
                        </a>
                    </li>
                    @endif
                    <li>
                        <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        <i class="material-icons">input</i>
                                        <span>Sign Out</span>
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                </form>
                    </li>
                    @endrole

                </ul>
            </div>
            <!-- #Menu -->
            <!-- Footer -->
            <div class="legal">
                <div class="copyright">
                    &copy; 2020 <a href="https://dma-bd.com">Datasoft Manufacturing & Assembly Inc. Ltd.</a>.
                    <p>Beta Version1.6.20</p>
                </div>
            </div>
        </aside>
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script>
$(document).ready(function (){
    if(sessionStorage.getItem("roomId") != ""){
        $(".btn-group").css("display", "none");
    }else {
        $(".btn-group").css("display", "inline-block");
    }
})
</script>

resources/views/layouts/backend/partial/topbar.blade.php
<nav class="navbar">
        <div class="container-fluid">
            <div class="navbar-header">
                <!-- <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a> -->
                <a href="javascript:void(0);" class="bars"></a>
                <img src="{{asset('public/DMA.gif')}}" href="" style="height: 45px; width: 85px;"><span class="badge bg-blue" style="font-weight: bold;font-size: 18px"> VirtualOffice</span><a class="navbar-brand" href=""></a>

            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse">
                <ul class="nav navbar-nav navbar-right">

                    <!-- Notifications -->
                    <!-- <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button">
                            <i class="material-icons">notifications</i>
                            <span class="label-count">7</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">NOTIFICATIONS</li>
                            <li class="body">
                                <ul class="menu">
                                    <li>
                                        <a href="javascript:void(0);">
                                            <div class="icon-circle bg-light-green">
                                                <i class="material-icons">person_add</i>
                                            </div>
                                            <div class="menu-info">
                                                <h4>12 new members joined</h4>
                                                <p>
                                                    <i class="material-icons">access_time</i> 14 mins ago
                                                </p>
                                            </div>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0);">
                                            <div class="icon-circle bg-cyan">
                                                <i class="material-icons">add_shopping_cart</i>
                                            </div>
                                            <div class="menu-info">
                                                <h4>4 sales made</h4>
                                                <p>
                                                    <i class="material-icons">access_time</i> 22 mins ago
                                                </p>
                                            </div>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0);">
                                            <div class="icon-circle bg-red">
                                                <i class="material-icons">delete_forever</i>
                                            </div>
                                            <div class="menu-info">
                                                <h4><b>Nancy Doe</b> deleted account</h4>
                                                <p>
                                                    <i class="material-icons">access_time</i> 3 hours ago
                                                </p>
                                            </div>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0);">
                                            <div class="icon-circle bg-orange">
                                                <i class="material-icons">mode_edit</i>
                                            </div>
                                            <div class="menu-info">
                                                <h4><b>Nancy</b> changed name</h4>
                                                <p>
                                                    <i class="material-icons">access_time</i> 2 hours ago
                                                </p>
                                            </div>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0);">
                                            <div class="icon-circle bg-blue-grey">
                                                <i class="material-icons">comment</i>
                                            </div>
                                            <div class="menu-info">
                                                <h4><b>John</b> commented your post</h4>
                                                <p>
                                                    <i class="material-icons">access_time</i> 4 hours ago
                                                </p>
                                            </div>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0);">
                                            <div class="icon-circle bg-light-green">
                                                <i class="material-icons">cached</i>
                                            </div>
                                            <div class="menu-info">
                                                <h4><b>John</b> updated status</h4>
                                                <p>
                                                    <i class="material-icons">access_time</i> 3 hours ago
                                                </p>
                                            </div>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0);">
                                            <div class="icon-circle bg-purple">
                                                <i class="material-icons">settings</i>
                                            </div>
                                            <div class="menu-info">
                                                <h4>Settings updated</h4>
                                                <p>
                                                    <i class="material-icons">access_time</i> Yesterday
                                                </p>
                                            </div>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="footer">
                                <a href="javascript:void(0);">View All Notifications</a>
                            </li>
                        </ul>
                    </li> -->
                    <!-- #END# Notifications -->

                    <li class="pull-right"><a href="javascript:void(0);" class="js-right-sidebar" data-close="true"><i class="material-icons">more_vert</i></a></li>
                </ul>
            </div>
        </div>
    </nav>